# Generated by Django 4.1.7 on 2023-02-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_playlist_creator_alter_playlist_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='song',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='creator',
            new_name='username',
        ),
    ]
